# Generated by Django 5.0.6 on 2024-05-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='contact_number',
            field=models.CharField(default='9999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='passenger',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
    ]
