# Generated by Django 5.0.6 on 2024-05-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passenger_contact_number_passenger_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
    ]
